---
title: "1A Solutions - Data types and type conversion"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this document we will briefly practice working with different vector types.  Follow the instructions in the comments of each code chunk.

## Exercise 1 - Creating and examining vectors

```{r}
# In a recent coding competition, Liz came first, Alex came second 
# and Jiena came third.

# here is a vector with their names
name <- c("Alex", "Jiena", "Liz")

# Check that this vector is a character vector of length 3
str(name)
```

```{r}
# Create a corresponding numeric vector with each person's position.
position <- c(2, 3, 1)
```

```{r}
# Check that your vector is a numeric vector of length three.
str(position)
```

## Exercise 2 - Converting vectors to factors and ordered factors 

```{r}
# Convert the 'name' character vector to a factor vector called 'name_factor'.
# Check that the conversion succeeded.
name_factor <- as.factor(name)
str(name_factor)
```


```{r}
# Convert your 'name' character vector to an ordered factor vector
# in increasing position order. Check that the conversion succeeded. 
name_ordered <- ordered(name, levels = c("Jiena", "Alex", "Liz"))
str(name_ordered)
```

```{r}
# EXTENSION: Use a function to display the vector in order of position (highest to lowest)?
sort(name_ordered, decreasing = TRUE)
```

