---
title: "6 - Graph Metrics and Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this document we will practice various types of network analyses using an edgelist of dolphins

## Exercise 1 - Basic graph summary metrics

```{r}
# Download the dolphin dataset from the URL provided
url <- "https://ona-book.org/data/dolphins.csv"

dolphin_edgelist <- read.csv(url)

# look at the data to see what you're dealing with
```

```{r}
# create an undirected graph

```

```{r}
# View the graph object - how many vertices and edges are there?

```


```{r}
# what is the distance between Zig and Fork


```

```{r}
# How large is the network?

```


```{r}
# Is this a dense network?

```

```{r}
# How many components are in this network?


# What does this mean for our network?

```

```{r}
# What is the network diameter? What does this mean?


```

```{r}
# how large is the largest clique?


# how many cliques are between size 3 and 5?

```

## Exercise 2 - Centrality measures

```{r}
# Continuing with our same dolphin graph, which dolphin is an important connector?

# SN100 has highest between centrality


# Which dolphin has the most connections? 

# Which dolphin has the most central? 


```

```{r}
# plot the dolphin graph and locate our highly central dolphins to see if these results make intuitive sense


```


## Exercise 3: Community detection

```{r}
# What communities do you see in the dolphin graph? Try out a couple of methods and compare results
# e.g. cluster_louvain, cluster_leiden, cluster_fast_greedy

```

```{r}
# plot your favorite option

```

## Exercise 4 - Do people tend to email with people in their same department?

```{r}
# Download the email dataset from the URL provided
url <- "https://ona-book.org/data/email_edgelist.csv"

email_edgelist <- read.csv(url)

# Download the corresponding department mappings from the URL provided
url_v <- "https://ona-book.org/data/email_vertices.csv"

email_dept <- read.csv(url_v)

# look through the edges and vertices to understand the data source
```

```{r}
# create the graph with vertice labels

# Calculate assortativity

```

## Exercise 5 - Exploring the friends graph (EXTENSION)

```{r}
# Download the friends dataset from the URL provided
url <- "https://ona-book.org/data/friends_tv_edgelist.csv"

friends_edgelist <- read.csv(url)
```

```{r}
# which two characters interact most?


# is this a connected network?


# who is the most "important" character?



```

```{r}
# Are the friends part of the same community?  Who else is in the community?  
# Does it make intuitive sense (if you're a friends fan :-) )

```


