---
title: "Wrapping up"
subtitle: "Thanks and follow-up"
author: "<b>rstudio::</b>conf(2022)"
output:
  xaringan::moon_reader:
    css: "style.css"
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

class: left, middle, rstudio-logo, bigfont

## Thank you

&#128591; This is the first time we have run this workshop.  **Thank you** for being a part of it!

&#128214; All the material is open source and freely available.  All your RStudio Cloud work will remain in your account for your future reference and use.

&#129489;&#8205;&#127891; Our faculty can view/review your work on RStudio Cloud if you want us to - just tag one or all of us on our [Github Discussions](https://github.com/rstudio-conf-2022/people-analytics-rstats/discussions) page.  We will also continue to monitor that page for questions in the coming days and weeks.


---
class: left, middle, rstudio-logo, small

## Ideas for future learning

* As we mentioned at the beginning of the workshop, we've really only had time to look at two very important topics that are most commonly used in people analytics
* Other, more general, courses you could consider in the future include:
 - **Natural Language Processing (NLP)**:  Particularly if you deal with a lot of text data
 - **Tidyverse**: For general data manipulation, reporting and wrangling
 - **Machine Learning**:  For more predictive analytics applications
 - **Shiny**:  For building front end data reporting applications
* Our team works with all of these and more, and we'd be happy to talk to any of you about our work during the remaining days of the conference 


---
class: left, middle, rstudio-logo, small

## Finally, feedback!

* You feedback is extremely important to us:
 - Helps us shape future People Analytics workshops
 - Helps inform curriculum and format decisions for future conf workshops
* Please complete the survey at https://rstd.io/conf-workshop-survey
* You'll also get this via email, but if you have time to do it now, please do so!
